Create empty `glyf` table when one is missing
CBDT/CBLC fonts made to draft version of the spec might not
contain a `glyf` table. This will make diffenator choke on CBDT
fonts right away.

Adding a faux table will prevent many errors like:

fontTools.ttLib.TTLibError: Font contains no outlines

TODO: Metrics calculated from these faux glyphs are obviously
going to be wrong